export const testIds = {
  appLoader: {
    container: 'app-loader',
    inline: 'inline-app-loader',
  },
  appConfig: {
    apiKey: 'data-testid ac-api-key',
    apiUrl: 'data-testid ac-api-url',
    settingsTab: (id: string) => `data-testid ac-settings-tab-${id}`,
    settingsTabPanel: (id: string) => `data-testid ac-settings-tab-panel-${id}`,
    unsavedChangesNotice: 'data-testid ac-unsaved-changes-notice',
    maxTotalTokens: 'data-testid ac-max-total-tokens',
    submit: 'data-testid ac-submit-form',
    useBuiltInMCPToggle: 'data-testid ac-use-builtin-mcp-toggle',
    addMcpServerButton: 'data-testid ac-add-mcp-server',
    saveMcpServersButton: 'data-testid ac-save-mcp-servers',
    mcpServerCard: (id: string) => `data-testid ac-mcp-server-${id}`,
    mcpServerNameInput: (id: string) => `data-testid ac-mcp-server-name-${id}`,
    mcpServerUrlInput: (id: string) => `data-testid ac-mcp-server-url-${id}`,
    mcpServerRemoveButton: (id: string) => `data-testid ac-mcp-server-remove-${id}`,
    mcpServerAdvancedToggle: (id: string) => `data-testid ac-mcp-server-advanced-${id}`,
    mcpServerAddHeaderButton: (id: string) => `data-testid ac-mcp-server-add-header-${id}`,
    mcpServerHeaderKeyInput: (id: string, index: number) => `data-testid ac-mcp-server-header-key-${id}-${index}`,
    mcpServerHeaderValueInput: (id: string, index: number) => `data-testid ac-mcp-server-header-value-${id}-${index}`,
    mcpServerHeaderRemoveButton: (id: string, index: number) =>
      `data-testid ac-mcp-server-header-remove-${id}-${index}`,
    manageToolsButton: (id: string) => `data-testid ac-manage-tools-${id}`,
    manageToolsModal: 'data-testid ac-manage-tools-modal',
    manageToolsToolItem: (toolName: string) => `data-testid ac-manage-tool-item-${toolName}`,
    promptEditor: {
      system: 'ac-prompt-system',
    },
    skills: {
      section: 'data-testid ac-skills-section',
      card: (name: string) => `data-testid ac-skill-card-${name}`,
      toggle: (name: string) => `data-testid ac-skill-toggle-${name}`,
      editButton: (name: string) => `data-testid ac-skill-edit-${name}`,
      resetButton: (name: string) => `data-testid ac-skill-reset-${name}`,
      deleteButton: (name: string) => `data-testid ac-skill-delete-${name}`,
      addButton: 'data-testid ac-skill-add',
      editorModal: 'data-testid ac-skill-editor-modal',
      editorTextarea: 'data-testid ac-skill-editor-textarea',
      editorSaveButton: 'data-testid ac-skill-editor-save',
      editorResetButton: 'data-testid ac-skill-editor-reset',
    },
    displaySettings: 'data-testid ac-display-settings',
    kioskModeField: 'data-testid ac-kiosk-mode-field',
    kioskModeToggle: 'data-testid ac-kiosk-mode-toggle',
    chatPanelPositionField: 'data-testid ac-chat-panel-position-field',
    chatPanelPositionSelector: 'data-testid ac-chat-panel-position-selector',
    saveDisplaySettingsButton: 'data-testid ac-save-display-settings',
    serviceGraphMaxNodes: 'data-testid ac-service-graph-max-nodes',
    serviceGraphMaxEdges: 'data-testid ac-service-graph-max-edges',
    graphitiAutoSaveToggle: 'data-testid ac-graphiti-auto-save-toggle',
    sessionTTLDays: 'data-testid ac-session-ttl-days',
    graphitiEpisodeTTLDays: 'data-testid ac-graphiti-episode-ttl-days',
    refreshServiceGraphButton: 'data-testid ac-refresh-service-graph',
    serviceGraphSummary: 'data-testid ac-service-graph-summary',
    saveServiceGraphSettingsButton: 'data-testid ac-save-service-graph-settings',
    externalMcpSection: 'data-testid ac-external-mcp-section',
    externalMcpPresetCard: (id: string) => `data-testid ac-external-mcp-preset-${id}`,
    externalMcpPresetAddButton: (id: string) => `data-testid ac-external-mcp-preset-add-${id}`,
    externalMcpPresetRemoveButton: (id: string) => `data-testid ac-external-mcp-preset-remove-${id}`,
    externalMcpPresetClientIdInput: (id: string) => `data-testid ac-external-mcp-preset-client-id-${id}`,
    externalMcpGenericForm: 'data-testid ac-external-mcp-generic-form',
    externalMcpGenericAddButton: 'data-testid ac-external-mcp-generic-add',
  },
  home: {
    container: 'data-testid home-container',
  },
  chat: {
    newChatButton: 'data-testid chat-new-chat-button',
    retryButton: 'data-testid chat-retry-button',
    mcpConnectionsButton: 'data-testid chat-mcp-connections-button',
    mcpConnectionsModal: 'data-testid chat-mcp-connections-modal',
    mcpConnectionRow: (id: string) => `data-testid chat-mcp-connection-${id}`,
    mcpConnectionConnect: (id: string) => `data-testid chat-mcp-connection-connect-${id}`,
    mcpConnectionDisconnect: (id: string) => `data-testid chat-mcp-connection-disconnect-${id}`,
    skillCommandMenu: 'data-testid chat-skill-command-menu',
    skillCommandItem: (name: string) => `data-testid chat-skill-command-item-${name}`,
    activeSkillHint: (name: string) => `data-testid chat-active-skill-${name}`,
    skillChip: (name: string) => `data-testid chat-skill-chip-${name}`,
    openDashboardButton: 'data-testid chat-open-dashboard-button',
  },
  investigation: {
    error: 'data-testid investigation-error',
  },
};
